# Generated by Django 4.2.4 on 2025-06-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'location', 'start_time', 'end_time')},
        ),
    ]
